---
- name: Catch Dynatrace Problems using Webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 35002
        
  rules:
    - name: Web site is DOWN
      condition: event.payload.ProblemTitle == "Http monitor outage"
      action:
        run_job_template:
          name: "RHEL - Deploy App using Podman"
          organization: Default
          job_args:
            extra_vars:
              _hosts: "{{ event.payload.EntityName }}"
              
    - name: Catch all remaining
      condition: event.payload is defined
      action:
        debug:
          var: event.payload.State
