- name: Golfball events
  hosts: localhost
  sources:
    - kubealex.eda.mqtt:
        host: "{{ host}}"
        port: "{{ port}}"
        topic: "{{ topic }}"

  rules:
    - name: New golfball event
      condition: event.meta is defined
      action:
        debug:
