---
- name: Check the status of a webpage
  hosts: localhost
  ## Define our source for events
  sources:
     - ansible.eda.url_check:
        urls:
          - http://{{ webserver_hostname }}
        delay: 30

  rules:
    - name: Web site is DOWN
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: "URL Checker - DOWN"
          organization: Default
          job_args:
            extra_vars:
              _hosts: "{{ webserver_hostname }}"
