---
- name: Respond to Zabbix Events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Web site is DOWN
      condition: event.payload.trigger_name == "url_checker"
      action:
        run_job_template:
          name: "URL Checker - DOWN"
          organization: Default
          job_args:
            extra_vars:
              _hosts: "{{ event.payload.host_host }}"

      - name: EC2 VM is Unresponsive
      condition: event.payload.trigger_name == "ICMP: Unavailable by ICMP ping"
      action:
        run_job_template:
          name: "Cloud / AWS / Restart VM"
          organization: Default
          job_args:
            extra_vars:
              vm_name: "{{ event.payload.host_host }}"
              
      - name: Debug
        condition: event.payload is defined
        action:
          debug:
            msg: "{{ event.payload }}"
