---
- name: Respond to Zabbix Events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Debug
      condition: event.payload is defined
      action:
        debug:
          msg: "You said, '{{ event.payload.message }}'. Is it me you're looking for?"
