---
- name: Respond to Zabbix Events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 35001

  rules:
    - name: Web site is DOWN
      condition: event.payload.trigger_name == "{{ trigger_name_selinux }}"
      action:
        run_job_template:
          name: "{{ job_name_selinux }}"
          organization: Default
          job_args:
            extra_vars:
              _hosts: "{{ event.payload.host_host }}"
